# Generated by Django 2.1.3 on 2018-11-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('terminal_id', models.CharField(max_length=10)),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
