# Generated by Django 2.1.3 on 2018-11-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_order',
            field=models.DateField(auto_now=True),
        ),
    ]
