# Generated by Django 2.1.3 on 2018-11-25 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_date_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
