# Generated by Django 2.1.3 on 2018-11-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20181125_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_token',
            field=models.CharField(max_length=20),
        ),
    ]
