# Generated by Django 2.1.3 on 2018-11-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20181125_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token_reponse',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
