# Generated by Django 2.1.3 on 2018-11-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20181125_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_response',
            field=models.CharField(max_length=100),
        ),
    ]
