# Generated by Django 2.1.3 on 2018-11-25 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='total_amount',
            new_name='value',
        ),
    ]
